# Generated by Django 4.2.2 on 2024-05-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0002_payment_made_payment_made_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_made_comments',
            name='debit_note',
        ),
        migrations.RemoveField(
            model_name='payment_made_history',
            name='recurring_invoice',
        ),
        migrations.AddField(
            model_name='payment_made_comments',
            name='payment_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payment_made'),
        ),
        migrations.AddField(
            model_name='payment_made_history',
            name='payment_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payment_made'),
        ),
    ]
