# Generated by Django 4.2.2 on 2024-05-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_remove_payment_made_comments_debit_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_made_bills',
            name='action',
        ),
    ]
