# Generated by Django 4.2.2 on 2024-05-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_rename_source_of_supply_of_supply_payment_made_source_of_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
