# Generated by Django 4.2.2 on 2024-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_payment_made_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_made_bills',
            name='bill_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
